# https://packit.dev/docs/configuration/

specfile_path: koji-osbuild.spec

synced_files:
    - koji-osbuild.spec
    - .packit.yaml

upstream_package_name: koji-osbuild
downstream_package_name: koji-osbuild

copy_upstream_release_description: true

upstream_tag_template: v{version}

actions:
  get-current-version: bash -c "git describe --tags --abbrev=0 | sed 's|v||'"

jobs:
- job: propose_downstream
  trigger: release
  metadata:
    dist_git_branches:
      - fedora-all
- job: koji_build
  trigger: commit
  metadata:
    dist_git_branches:
      - fedora-all
