FROM registry.access.redhat.com/ubi8/ubi:latest

COPY test/container/rhel.repo /etc/yum.repos.d/
COPY test/container/brew.repo /etc/yum.repos.d/

RUN dnf -y upgrade \
    && dnf -y \
	--setopt=fastestmirror=True \
	--setopt=install_weak_deps=False \
	install \
	koji-builder \
	koji-utils \
	python3-koji \
	python3-requests \
	&& dnf clean all

COPY test/container/builder/kojid.conf /etc/kojid/kojid.conf
COPY plugins/builder/osbuild.py /usr/lib/koji-builder-plugins/
COPY test/container/builder/run-kojid.sh /app/run-kojid.sh
COPY test/container/builder/osbuild.krb5.conf /etc/krb5.conf.d/

ENTRYPOINT /app/run-kojid.sh
