FROM registry.access.redhat.com/ubi8/ubi:latest

COPY test/container/rhel.repo /etc/yum.repos.d/
COPY test/container/brew.repo /etc/yum.repos.d/

# koji db schema is in docs, remove nodocs from from dnf config
RUN sed  -i '/^tsflags=nodocs$/d' /etc/dnf/dnf.conf

RUN dnf -y upgrade \
    && dnf -y \
            --setopt=fastestmirror=True \
            --setopt=install_weak_deps=False \
	install \
	koji-hub \
	postgresql \
	mod_ssl \
	koji-web \
	python3-jsonschema \
	&& dnf clean all

COPY test/container/hub/hub.conf /etc/koji-hub/hub.conf
COPY test/container/hub/ssl.conf /etc/httpd/conf.d/ssl.conf
COPY plugins/hub/osbuild.py /usr/lib/koji-hub-plugins/
COPY test/container/hub/run-hub.sh /app/run-hub.sh

COPY test/container/hub/web.conf /etc/kojiweb/web.conf
COPY test/container/hub/kojiweb.conf /etc/httpd/conf.d/kojiweb.conf

ENTRYPOINT /app/run-hub.sh
