ARG version=latest

FROM docker.io/library/fedora:$version

# koji db schema is in docs, remove nodocs from from dnf config
RUN sed  -i '/^tsflags=nodocs$/d' /etc/dnf/dnf.conf

RUN dnf -y upgrade \
    && dnf -y \
            --setopt=fastestmirror=True \
            --setopt=install_weak_deps=False \
            install \
	koji-hub \
	koji-web \
        postgresql \
        mod_ssl \
	python3-jsonschema \
	&& dnf clean all

COPY container/hub/hub.conf /etc/koji-hub/hub.conf
COPY container/hub/ssl.conf /etc/httpd/conf.d/ssl.conf
COPY container/hub/run-hub.sh /app/run-hub.sh

COPY container/hub/web.conf /etc/kojiweb/web.conf
COPY container/hub/kojiweb.conf /etc/httpd/conf.d/kojiweb.conf

ENTRYPOINT /app/run-hub.sh
